<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category  BSS
 * @package   Bss_FacebookPixel
 * @author    Extension Team
 * @copyright Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license   http://bsscommerce.com/Bss-Commerce-License.txt
 */

/**
 * @var $block \Bss\FacebookPixel\Block\Code
 */

$data   = $block->getFacebookPixelData();
$id     = $data['id'];
$action = $data['full_action_name'];
$listDisableCode = $block->listDisableCode();

?>
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.agent='dvapptrian';n.queue=[];
t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');

fbq('init', '<?php echo $block->escapeHtml($id) ?>');

<?php if ($action == 'catalog_product_view') : ?>
fbq('track', 'PageView');
<?php
$productData = $block->getProductData();
if ($productData !== null) : ?>
fbq('track', 'ViewContent', {
    content_name: '<?php echo $block
        ->escapeHtml($productData['content_name']) ?>',
    content_ids: ['<?php echo $block
        ->escapeHtml($productData['content_ids']) ?>'],
    content_type: 'product',
    value: <?php echo $block->escapeHtml($productData['value']) ?>,
    currency: '<?php echo $block->escapeHtml($productData['currency']) ?>'
});
//Add Pixel Events to the button's click handler
if (typeof jQuery != 'undefined') {
    jQuery('#product-addtocart-button').click(function() {
        fbq('track', 'AddToCart', {
            content_name: '<?php echo $block
                ->escapeHtml($productData['content_name']) ?>',
            content_ids: ['<?php echo $block
                ->escapeHtml($productData['content_ids']) ?>'],
            content_type: 'product',
            value: <?php echo $block->escapeHtml($productData['value']) ?>,
            currency: '<?php
                echo $block->escapeHtml($productData['currency']) ?>'
        });
    });
}
<?php endif; ?>
<?php elseif ($action == 'catalogsearch_result_index' && !in_array('search_page', $listDisableCode)) : ?>
fbq('track', 'PageView');
fbq('track', 'Search');
<?php elseif ($action == 'catalogsearch_advanced_result' && !in_array('advanced_search_page', $listDisableCode)) : ?>
fbq('track', 'PageView');
fbq('track', 'Search');
<?php elseif ($action == 'customer_account_create' && !in_array('registration_page', $listDisableCode)) : ?>
fbq('track', 'PageView');
fbq('track', 'CompleteRegistration');
<?php elseif (($action == 'checkout_index_index'
    || $action == 'onepagecheckout_index_index'
    || $action == 'onestepcheckout_index_index'
    || $action == 'opc_index_index') && !in_array('checkout_page', $listDisableCode)) : ?>
fbq('track', 'PageView');
fbq('track', 'InitiateCheckout');
<?php elseif (($action == 'checkout_onepage_success'
    || $action == 'onepagecheckout_index_success') && !in_array('success_page', $listDisableCode) ) : ?>
fbq('track', 'PageView');
<?php
    echo $block->getChildHtml(
        'bss.facebook.pixel.success.purchase'
    );
?>
<?php elseif ($action == 'wishlist_index_index') : ?>
fbq('track', 'PageView');
fbq('track', 'AddToWishlist');
<?php elseif ($action == 'catalog_category_view') :?>
fbq('track', 'PageView');
<?php
try {
    $categoryData = $block->getCategoryData();
} catch (\Magento\Framework\Exception\NoSuchEntityException $e) {
}
if ($categoryData !== null) : ?>
fbq('track', 'ViewContent', {
    content_name: '<?php echo $block
        ->escapeHtml($categoryData['content_name']) ?>',
    content_ids: ['<?php echo $block
        ->escapeHtml($categoryData['content_ids']) ?>'],
    content_type: 'category',
    currency: '<?php echo $block->escapeHtml($categoryData['currency']) ?>'
});
<?php endif; ?>
<?php elseif ($action == 'customer_account_index' && !in_array('account_page', $listDisableCode) ) : ?>
fbq('track', 'PageView');
<?php elseif(!in_array('cms_page', $listDisableCode)) : ?>
fbq('track', 'PageView');
<?php endif; ?>

</script>
<noscript><img height="1" width="1" style="display:none" alt="Facebook Pixel" 
src="https://www.facebook.com/tr?id=<?php
    echo $block->escapeHtml($id) ?>&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->
