<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category  BSS
 * @package   Bss_FacebookPixel
 * @author    Extension Team
 * @copyright Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license   http://bsscommerce.com/Bss-Commerce-License.txt
 */

/**
 * @var $block \Bss\FacebookPixel\Block\Purchase
 */

$orderData = $block->getOrderData();
if ($orderData !== null) :?>
fbq('track', 'Purchase', {
<?php if (array_key_exists('content_name', $orderData)) : ?>
    content_name: '<?php echo $block->escapeHtml($orderData['content_name'])?>',
<?php endif; ?>
    content_ids: [<?php /* @noEscape */ echo $orderData['content_ids'] ?>],
    content_type: 'product',
    value: <?php echo $block->escapeHtml($orderData['value']) ?>,
    currency: '<?php echo $block->escapeHtml($orderData['currency']) ?>'
});
<?php endif; ?>
